from abc import ABC, abstractmethod
from typing import Any, Optional


class IApiClient(ABC):
    @abstractmethod
    def get(self, path: str, params: Optional[dict] = None) -> Any: ...
    @abstractmethod
    def post(self, path: str, json: dict) -> Any: ...
    @abstractmethod
    def patch(self, path: str, json: dict) -> Any: ...
    @abstractmethod
    def delete(self, path: str) -> Any: ...
    @abstractmethod
    def check_status(self) -> bool: ...


class ITransactionRepository(ABC):
    @abstractmethod
    def get_transactions(self, month: str = "", category: str = "", type_: str = "") -> list: ...
    @abstractmethod
    def create_transaction(self, data: dict) -> dict: ...
    @abstractmethod
    def update_transaction(self, id: str, data: dict) -> dict: ...
    @abstractmethod
    def delete_transaction(self, id: str) -> dict: ...
    @abstractmethod
    def bulk_delete_transactions(self, ids: list[str]) -> dict: ...
    @abstractmethod
    def cache_transactions(self, transactions: list, month: str): ...


class IBudgetRepository(ABC):
    @abstractmethod
    def get_budgets(self, month: str = "") -> list: ...
    @abstractmethod
    def get_budget_status(self, month: str) -> list: ...
    @abstractmethod
    def create_budget(self, data: dict) -> dict: ...
    @abstractmethod
    def update_budget(self, id: str, data: dict) -> dict: ...
    @abstractmethod
    def delete_budget(self, id: str) -> dict: ...
    @abstractmethod
    def bulk_delete_budgets(self, ids: list[str]) -> dict: ...
    @abstractmethod
    def cache_budgets(self, budgets: list, month: str): ...


class IGoalRepository(ABC):
    @abstractmethod
    def get_goals(self) -> list: ...
    @abstractmethod
    def create_goal(self, data: dict) -> dict: ...
    @abstractmethod
    def deposit_to_goal(self, id: str, amount: float) -> dict: ...
    @abstractmethod
    def delete_goal(self, id: str) -> dict: ...
    @abstractmethod
    def bulk_delete_goals(self, ids: list[str]) -> dict: ...
    @abstractmethod
    def cache_goals(self, goals: list): ...


class IStatsRepository(ABC):
    @abstractmethod
    def get_summary(self, month: str) -> dict: ...
    @abstractmethod
    def get_category_stats(self, month: str) -> dict: ...
    @abstractmethod
    def get_trends(self, months: int = 6) -> list: ...
    @abstractmethod
    def get_top_expenses(self, month: str, limit: int = 5) -> list: ...
    @abstractmethod
    def get_heatmap(self, month: str) -> dict: ...


class IExchangeRateRepository(ABC):
    @abstractmethod
    def get_exchange_rates(self) -> dict: ...


class ICacheRepository(ABC):
    @abstractmethod
    def get_rate(self, base: str, target: str) -> float | None: ...
    @abstractmethod
    def cache_rates(self, base: str, rates: dict): ...

    @abstractmethod
    def get_cached_transactions(self, month: str = "") -> list: ...
    @abstractmethod
    def cache_transactions(self, transactions: list, month: str): ...

    @abstractmethod
    def get_cached_budgets(self, month: str = "") -> list: ...
    @abstractmethod
    def cache_budgets(self, budgets: list, month: str): ...

    @abstractmethod
    def get_cached_goals(self) -> list: ...
    @abstractmethod
    def cache_goals(self, goals: list): ...
